### ISSUE TITLE
Can't  check specificity in some genome[KeyError]

### ISSUE THREAD

**Issue by JianMingLuo** [billzt/PrimerServer2#13]
**hi,thanks for your great software!

When I plan to use full mode to design primers and check primer specificity, or check primer specificity, the progress bar of the task will run all the time. I checked the error and found that it displayed keyerror: 'GB | cm223420.1 |: 1023-1042'.
I have 10 genomes and found this problem in two of them. What caused this mistake?

The following is the complete error code:
Traceback (most recent call last):
File "/home/ljm/.conda/envs/PrimerServer/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/home/ljm/.conda/envs/PrimerServer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/prim          erserver2/core/run_blast.py", line 48, in run_ blast
report_ amplicons = filter_ Tm(amplicons['amplicons'], query_primer_seq=query_primer_seq_dict, \
File "/home/ljm/.conda/envs/PrimerServer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/prim          erserver2/core/analysis_blast.py", line 123, in filter_ Tm
hit_ seq_ minus = rev_ complement(hits_seqs[region_minus])  # samtools faidx hasn't do rev_ complement yet
KeyError: 'gb|Cm223420.1|:1023-1042'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/ljm/.conda/envs/PrimerServer/bin/primertool", line 33, in <module>
sys.exit(load_entry_point('primerserver2==2.0.0b21', 'console_scripts', 'primertool')())
File "/home/ljm/.conda/envs/PrimerServer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/prim          erserver2/cmd/primertool.py", line 204, in main
run(args)
File "/home/ljm/.conda/envs/PrimerServer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/prim          erserver2/cmd/primertool.py", line 167, in run
primers = run_ blast. run_ blast_ parallel(primers=primers, dbs=dbs, cpu=args.cpu,\
File "/home/ljm/.conda/envs/PrimerServer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/prim          erserver2/core/run_blast.py", line 108, in run_ blast_ parallel
result_ data = result. get()  # db and amplicons
File "/home/ljm/.conda/envs/PrimerServer/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._ value
KeyError: 'gb|Cm223420.1|:1023-1042'

**Comment by tao-bioinfo** [comment]
Hello, can you show me what's your input and parameters? (If the file is big, give a part of sequence is OK)

**Comment by JianMingLuo** [comment]
> Hello, can you show me what's your input and parameters? (If the file is big, give a part of sequence is OK)

i use it on web UI,i only input the geneID,the region type is Include Region

![image](https://user-images.githubusercontent.com/112245781/188301679-a94f0a24-25c9-4da1-be03-53e08f1d7581.png)

the genome fatsa is: http://citrus.hzau.edu.cn/data/Genome_info/RL.v1.0/RL.v1.0.CDS.fa

**Comment by tao-bioinfo** [comment]
I download the template fasta (in fact it is CDS, not genome) and run command like this (input is your iD: Cm000010.1):
```
primertool full input RL.v1.0.CDS.fa --type SEQUENCE_INCLUDED_REGION -a --checking-size-max 300 --Tm-diff 10 --primer-num-return 10
```

There is no error

**Comment by tao-bioinfo** [comment]
Please be note that genome has to be indexed by samtools first, and make sure the index file is correct

**Comment by JianMingLuo** [comment]
> Please be note that genome has to be indexed by samtools first, and make sure the index file is correct

It still can't work on my computer.I ensure the genome has benn indexed .I have 9 genome ,only 2 of them cant work.

**Comment by tao-bioinfo** [comment]
How about running in the command line?

**Comment by JianMingLuo** [comment]
> 

 primertool full 1.txt --type SEQUENCE_INCLUDED_REGION -a --checking-size-max 300 --Tm-diff 10 --primer-num-return 10 0012_Citrus_Medica_V1.0_HZAU_CDS.fasta

Here is my cmd,it cant work on web UI too.
